# Generated by Django 5.2.12 on 2026-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Планируется'), ('DONE', 'Проведено'), ('CANCELLED', 'Отменено')], max_length=20)),
            ],
        ),
    ]
