# Generated by Django 5.2.12 on 2026-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Обучается'), ('TRANSFERRED', 'Переведён'), ('GRADUATED', 'Выпущен'), ('EXPELLED', 'Отчислен'), ('ACADEMIC', 'Академический отпуск')], max_length=20),
        ),
    ]
