# Generated by Django 5.2.12 on 2026-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Утвержден'), ('IN_PROGRESS', 'В работе'), ('PRE_DEFENSE', 'Предзащита'), ('DEFENDED', 'Защищён'), ('REJECTED', 'Отклонён')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает начала'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('OVERDUE', 'Просрочен')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Не начата'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнена'), ('OVERDUE', 'Просрочена')], default='TODO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Принять'), ('NEEDS_REVISION', 'Вернуть на доработку')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='task_submissions/')),
                ('report', models.FileField(blank=True, null=True, upload_to='submission_reports/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Отправлено'), ('NEEDS_REVISION', 'На доработку'), ('APPROVED', 'Принято')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
