# Generated by Django 5.2.12 on 2026-05-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='stud.studentenrollment'),
        ),
    ]
