# Generated by Django 5.2.12 on 2026-05-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARTICLE', 'Статья'), ('THESIS', 'Тезисы'), ('CONFERENCE', 'Доклад')], default='ARTICLE', max_length=25)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='research.researchproject')),
            ],
        ),
    ]
