# Generated by Django 5.2.12 on 2026-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_seed_indexing_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantemplatetask',
            name='task_type',
            field=models.CharField(choices=[('FILE', 'File'), ('PUBLICATION', 'Publication')], default='FILE', max_length=25),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На рассмотрении'), ('PRINT', 'В печати'), ('PUBLISHED', 'Опубликована'), ('REJECTED', 'Отклонена')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagetask',
            name='task_type',
            field=models.CharField(choices=[('FILE', 'File'), ('PUBLICATION', 'Publication')], default='FILE', max_length=25),
        ),
    ]
